import Head from 'next/head';
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bamitex</title>
        <meta name="description" content="Generated by Bamitex" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h4>داشبورد</h4>
    </>
  );
}
